# Generated by Django 3.1.1 on 2020-09-21 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_auto_20200920_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='/mg/default.png', upload_to='profile_pics'),
        ),
    ]
