# Generated by Django 3.1.1 on 2020-09-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(upload_to='novels_images'),
        ),
    ]
