# Generated by Django 3.1.1 on 2020-09-15 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0005_novel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='status',
            field=models.CharField(choices=[('Andamento', 'Andamento'), ('Concluido', 'Concluido')], max_length=10),
        ),
    ]
