# Generated by Django 3.1.1 on 2020-12-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('novels', '0014_novel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='novel',
            name='image',
            field=models.ImageField(upload_to='novels_images'),
        ),
    ]
